version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: aro-shop-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: aro_shop
      MYSQL_USER: aro_user
      MYSQL_PASSWORD: aro_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    build: .
    container_name: aro-shop-app
    restart: always
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      DB_USER: aro_user
      DB_PASS: aro_password
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: aro_shop

volumes:
  db_data:
