apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root
            - name: MYSQL_DATABASE
              value: aro_shop
            - name: MYSQL_USER
              value: aro_user
            - name: MYSQL_PASSWORD
              value: aro_password
          ports:
            - containerPort: 3306
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql-storage
      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: mysql-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: aro-shop-service
spec:
  selector:
    app: aro-shop
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aro-shop-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aro-shop
  template:
    metadata:
      labels:
        app: aro-shop
    spec:
      containers:
        - name: aro-shop-container
          image: apipointofsale-app:latest
          imagePullPolicy: Never
          env:
            - name: DB_USER
              value: aro_user
            - name: DB_PASS
              value: aro_password
            - name: DB_HOST
              value: mysql-service
            - name: DB_PORT
              value: "3306"
            - name: DB_NAME
              value: aro_shop
          ports:
            - containerPort: 8080
