# Load .env secara manual untuk Git Bash
include .env
export $(shell grep -E '^[A-Z_]+=' .env | xargs)

MIGRATE=migrate -database "mysql://$(DB_USER):$(DB_PASS)@tcp($(DB_HOST):$(DB_PORT))/$(DB_NAME)" -path db/migrations

migrate-up:
	@$(MIGRATE) up

migrate-down:
	@$(MIGRATE) down 1

migrate-reset:
	@$(MIGRATE) down && $(MIGRATE) up

run:
	go run main.go


# migrate -database "mysql://root:@tcp(localhost:3306)/db_aro_shop" -path db/migrations up
# migrate -database "mysql://root:@tcp(localhost:3306)/db_aro_shop" -path db/migrations down
