name: CI/CD Deployment to VPS (Golang)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout kode
        uses: actions/checkout@v3

      - name: Setup Golang
        uses: actions/setup-go@v4
        with:
          go-version: 1.23

      - name: Build aplikasi
        run: |
          go mod tidy
          go build -o API-Point-Of-Sale main.go

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.VPS_IP }} >> ~/.ssh/known_hosts

      - name: Deploy ke VPS
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_IP }} << 'EOF'
            cd /var/www/myapp/API-Point-Of-Sale || exit 1
            git pull origin main || exit 1
            go build -o API-Point-Of-Sale main.go || exit 1
            sudo systemctl restart API-Point-Of-Sale.service || exit 1
          EOF

  