name: CI/CD Deployment to VPS (Golang)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout kode
        uses: actions/checkout@v3

      - name: Setup Golang
        uses: actions/setup-go@v4
        with:
          go-version: 1.23

      - name: Build aplikasi
        run: |
          go mod tidy
          go build -o myapp main.go

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.VPS_IP }} >> ~/.ssh/known_hosts

      - name: Deploy ke VPS
        run: |
          ssh ${{ secrets.VPS_USER }}@${{ secrets.VPS_IP }} << 'EOF'
            cd /var/www/app || git clone git@github.com:ARofiqi/API-Point-Of-Sale.git /var/www/app
            cd /var/www/app
            git reset --hard
            git pull origin main
            go mod tidy
            go build -o myapp main.go
            systemctl restart myapp.service
          EOF
