name: CI/CD Deployment to VPS (Golang with Docker Compose)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout kode
        uses: actions/checkout@v3

      - name: Setup Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose
          # docker.io 

      - name: Build Docker image
        run: |
          docker-compose build

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.VPS_IP }} >> ~/.ssh/known_hosts

      - name: Deploy dengan Docker Compose ke VPS
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_IP }} << 'EOF'
            # Pastikan Docker Compose sudah terpasang di VPS
            docker-compose -v || exit 1

            # Pindah ke direktori aplikasi di VPS
            cd /var/www/myapp || exit 1

            # Ambil perubahan terbaru dari Git
            git pull origin main || exit 1

            # Bangun ulang Docker image dan jalankan container
            docker-compose down || exit 1
            docker-compose up -d --build || exit 1
          EOF
